import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { mapTemplate, action } from "nanostores";
import { useStore } from "@nanostores/react";

const CellStore = mapTemplate<{
  id: string;
  value: number;
  open: boolean;
}>((newCell, id) => {
  newCell.setKey("id", id);
  newCell.setKey("value", 0);
  newCell.setKey("open", false);
});

const Cell = ({ id }: { id: string }) => {
  const cell = useStore(CellStore(id));

  const reveal = action(cell, "reveal", () => {
    cell.open = true;

    return cell;
  });

  return (
    <button
      onClick={() => {
        console.log(cell);
        reveal();
        console.log(cell);
      }}
      className="flex w-fit gap-2 bg-green-300"
    >
      <div>{id}</div>
      <div>{cell.open + ""}</div>
      <div>{cell.value}</div>
    </button>
  );
};

const Home: NextPage = () => {
  const cellArray = new Array(9).fill(0).map((_, i) => i);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid w-fit grid-cols-3 gap-2">
          {cellArray.map((i) => (
            <Cell id={i.toString()} />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
